# Generated by Django 4.1.2 on 2022-10-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_supplier_rename_books_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Economy', 'Economy'), ('Geography', 'Geography')], default='Math', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='favorite_genre',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Economy', 'Economy'), ('Geography', 'Geography')], default='Math', max_length=200),
        ),
    ]
