# Generated by Django 4.1.2 on 2022-10-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_book_genre_alter_customer_favorite_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
