# Generated by Django 4.1.2 on 2022-10-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Economy', 'Economy'), ('Geography', 'Geography'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Computer Science', 'Computer Science'), ('Other', 'Other')], default='Math', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='favorite_genre',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Economy', 'Economy'), ('Geography', 'Geography'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Computer Science', 'Computer Science'), ('Other', 'Other')], default='Math', max_length=200),
        ),
    ]
