# Generated by Django 4.1.2 on 2022-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_book_genre_alter_customer_favorite_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Biology_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='Chemistry_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='ComputerScience_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='Economy_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='English_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='Geography_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='Math_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='Other_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='Physics_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
