# Generated by Django 4.1.2 on 2022-10-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_biology_click_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Total_click_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
