# Generated by Django 4.1.2 on 2022-10-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_total_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Total_click_count',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
