# Generated by Django 4.1.2 on 2022-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('favorite_category', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Economy', 'Economy'), ('Geography', 'Geography'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Computer-science', 'Computer-science'), ('Other', 'Other')], default='Mathematics', max_length=200)),
                ('Math_click_count', models.PositiveIntegerField(default=1)),
                ('Physics_click_count', models.PositiveIntegerField(default=1)),
                ('Biology_click_count', models.PositiveIntegerField(default=1)),
                ('Economy_click_count', models.PositiveIntegerField(default=1)),
                ('Geography_click_count', models.PositiveIntegerField(default=1)),
                ('Chemistry_click_count', models.PositiveIntegerField(default=1)),
                ('English_click_count', models.PositiveIntegerField(default=1)),
                ('ComputerScience_click_count', models.PositiveIntegerField(default=1)),
                ('Other_click_count', models.PositiveIntegerField(default=1)),
                ('Total_click_count', models.PositiveIntegerField(default=9)),
            ],
        ),
    ]
